/* tslint:disable */
/* eslint-disable */
/**
 * Frontier Platform API
 *  ## Authentication This API uses token authentication (Bearer in HTTP Header). First you retrieve a new Bearer token using sign-in apis. After that you can use it to access other resources.  **Bearer token example**  `eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMxMyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImJyaWFuY2hvdTczMTBAZ21haWwuY29tIiwiZXhwIjoxNjI4NTE4OTgzLCJpc3MiOiJodHRwczovL3RleHRpbGUtd2ViYXBpLmZyb250aWVyLmNvb2wiLCJhdWQiOiJodHRwczovL3RleHRpbGUtd2ViYXBpLmZyb250aWVyLmNvb2wifQ.PNu0iU3x0QrGTjARx7W93B5Lsc8HRApdnHgTnTtOAr4`  ## Status codes This API uses HTTP status codes to communicate with the API. + `200 OK` - Response to a successful GET, PUT, PATCH or DELETE. + `400 Bad Request` - Malformed request; request body validation errors. + `401 Unauthorized` - When no or invalid authentication details are provided. + `403 Forbidden` - When authentication succeeded but authenticated user doesn\'t have access to the resource. + `415 Unsupported Media Type` - the server refuses to accept the request because the payload format is in an unsupported format ## Roles Each API endpoint has described minimal role to access. Only users with specific roles can access those endpoints. For insufficient role `403 Forbidden` HTTP response will be returned.  User roles:    + `11111 (Org Owner)` - the organization owner    + `222222 (Group Owner)` - the group owner  ## Representation of dates and times All exchange of date and time-related data MUST be done according to `Unix Timestamp` and stored in `UTC+0`. All dates in the API are numbers in the following format: `1628503326`.   ## pagination  > --- 
 *
 * The version of the OpenAPI document: 2.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "https://textile-webapi-dev.frontier.cool".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
    url: string;
    options: AxiosRequestConfig;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}
