#!/bin/sh
. "$(dirname $0)/_/husky.sh"

folders=($(git diff HEAD~1 --name-only | xargs dirname | sort | uniq))
isDisabled=true

for folder in "${folders[@]}"
do
  if [[ $folder != *"packages/i18n/locales"* ]];then
    npx start-server-and-test dev:platform 8080 test:e2e:normal
    break
  fi

   # or do whatever with individual element of the array
done
